### ISSUE TITLE
Is it ok to expose `config` field in TS types?

### ISSUE THREAD

**Issue by felixmosh** [ladjs/graceful#11]
My usage is a bit different, I'm creating an instance of `Graceful` and then pass it to services so they will register themself.

```ts
const graceful = new Graceful();

await createPendingPromotionsWorker({ db, graceful });
await createBulkChangePromotionsWorker({ db, graceful });
await createPriceQuotesWorker({ db, graceful });

graceful.listen();
```

Each one of these functions registers a shutdown function using `graceful.config.servers` / `graceful.config.customHandlers`.

Since `config` is a class property maybe it will be Ok to expose it as well in types?

If so, I'll prepare a PR for this :]

**Comment by Nicholaiii** [comment]
I think the more graceful (🥁) option would be adding functions to add handlers, rather than exposing internal fields.

**Comment by felixmosh** [comment]
Ok, maybe adding a public `addXHandlers` is a better option?

**Comment by niftylettuce** [comment]
PR welcome
