### ISSUE TITLE
Error: Cannot find module 'node:http' in ^3.0.1 version with Node v14.17.2

### ISSUE THREAD

**Issue by khanifikhsanudin** [ladjs/graceful#13]
## Describe the bug

**Node.js version:** v14.17.2

**Graceful version:** ^3.0.1

----------------------------------------

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:http'

**Comment by titanism** [comment]
We'll resolve this, one moment

**Comment by titanism** [comment]
Resolved in v3.0.2 and released to npm

https://github.com/ladjs/graceful/releases/tag/v3.0.2
