### ISSUE TITLE
Due to `promise.all` if one fails then all fail

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/graceful#2]
Need to rewrite so all get attempted and we log errors after all have finished failing or succeeding

**Comment by rohit-gohri** [comment]
Can use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

**Comment by niftylettuce** [comment]
Could you submit PR?

**Comment by rohit-gohri** [comment]
Sure, I'll try by the weekend. Though it's only supported in NodeJS >= 12.9

**Comment by felixmosh** [comment]
@niftylettuce did you encountered such case, which one of the stops rejected caused `Promise.all` to reject.

From a quick code review, I see that each `xStop` is wrapped with `try` & `catch` which means that it can't return a rejection... (https://github.com/ladjs/graceful/blob/master/index.js#L77-L81)
Am I right?

**Comment by niftylettuce** [comment]
Yeah, you're correct @felixmosh.  I think instead we should have it return an object of `errors: [], values: []` or something.  I'm open to opinions.
