### ISSUE TITLE
Feature request: Allow custom handlers

### ISSUE THREAD

**Issue by felixmosh** [ladjs/graceful#5]
I want to close mysql connection, I'm using Knex as an abstraction above it.

Knex has `destroy` method.

Instead of saving a list of services which should be terminated (and each time add new one) it is better to allow to pass a method which can return a promise, and inside, it will do it's cleanup.

**Comment by niftylettuce** [comment]
Thanks @felixmosh, v1.0.4 released to npm with this.

https://github.com/ladjs/graceful/releases/tag/v1.0.4
